{{- if .Values.orderService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aks-store-demo.labels" . | nindent 4 }}
    app: order-service
spec:
  type: {{ .Values.orderService.service.type }}
  ports:
    - port: {{ .Values.orderService.service.port }}
      targetPort: {{ .Values.orderService.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "aks-store-demo.selectorLabels" . | nindent 4 }}
    app: order-service
{{- end }}
